import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { api } from '../api/client'
import RoiDrawer from '../components/RoiDrawer'
import Breadcrumbs from '../components/Breadcrumbs'
import { getCameraMeta } from '../utils/hospitalMeta'

const fmt = v => { const s=Math.max(0,Math.floor(v||0)); return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}` }

export default function CameraDetail() {
  const { id } = useParams(); const camId=Number(id)
  const [camera,setCamera]=useState(null), [status,setStatus]=useState(null), [settings,setSettings]=useState(null), [events,setEvents]=useState([])
  const [calibrating,setCalibrating]=useState(false), [imgKey,setImgKey]=useState(0)
  const loadCamera=()=>api.cameras.list().then(all=>setCamera(all.find(c=>c.id===camId)))
  useEffect(()=>{ loadCamera(); api.settings.get().then(setSettings); api.events.list({camera_id:camId}).then(e=>setEvents(e.slice(0,6)))
    let alive=true; const poll=async()=>{try{const s=await api.cameras.status(camId);if(alive)setStatus(s)}catch{if(alive)setStatus(null)}};poll();const t=setInterval(poll,800);return()=>{alive=false;clearInterval(t)} },[camId])
  const timeline=useMemo(()=>{
    const rows=[]; const now=new Date().toLocaleTimeString()
    if(status?.is_auth) rows.push([now,'Face authenticated',status.user])
    if(status?.mask) rows.push([now,'Mask verified','PASS'])
    if(status?.hat) rows.push([now,'Hat verified','PASS'])
    if((status?.wash_time||0)>0) rows.push([now,'Hand washing in progress',fmt(status.wash_time)])
    if(status?.master_ready) rows.push([now,'WHO hand-wash steps completed','6 / 6'])
    if(status?.master_ready) rows.push([now,'Compliance achieved','COMPLIANT'])
    return rows
  },[status?.is_auth,status?.mask,status?.hat,status?.wash_time,status?.master_ready,status?.master_ready,status?.user])
  if(!camera)return <div className="empty-state">Loading camera…</div>
  const meta=getCameraMeta(camera), max=settings?.max_wash_time??40, min=settings?.min_wash_time??20, pct=Math.min(100,((status?.wash_time||0)/max)*100)
  const saveRoi=async roi=>{await api.cameras.update(camId,{manual_roi:roi});setCalibrating(false);loadCamera()}
  return <div>
    <Breadcrumbs items={[{label:meta.department,to:'/rooms'},{label:camera.room||'Unassigned Room',to:`/rooms/${encodeURIComponent(`${meta.department}::${camera.room||'Unassigned Room'}`)}`},{label:camera.name}]} />
    <div className="page-header camera-detail-title"><div><span className="eyebrow">{camera.room||'UNASSIGNED ROOM'}</span><h1 className="page-title">{camera.name} — {meta.purpose}</h1><div className="page-subtitle">{meta.type} · {camera.source}</div></div><span className={'large-status '+(status?.connected?'live':'offline')}><span className={'status-dot '+(status?.connected?'online':'offline')}/>{status?.connected?'LIVE':'OFFLINE'}</span></div>
    <div className="camera-detail-grid">
      <section className="video-panel card">
        {calibrating?<RoiDrawer imageSrc={api.streamUrl(camId)} initialRoi={camera.manual_roi} onSave={saveRoi} onCancel={()=>setCalibrating(false)}/>:<div className="detail-video cam-video-wrap"><img key={imgKey} src={api.streamUrl(camId)} alt={camera.name} onError={()=>setTimeout(()=>setImgKey(k=>k+1),2000)}/><div className="video-timestamp mono">{new Date().toLocaleTimeString()}</div></div>}
        {!calibrating&&<div className="video-actions"><span className="muted mono">AI overlays are generated by backend inference</span><div><button className="btn btn-sm" onClick={()=>setCalibrating(true)}>Draw scrub zone</button><button className="btn btn-sm" onClick={async()=>{await api.cameras.calibrate(camId);loadCamera()}}>Reset auto zone</button></div></div>}
      </section>
      <aside className="ai-status-panel card"><div className="panel-head"><span className="eyebrow">AI STATUS</span><strong>{status?.connected?'Monitoring':'No signal'}</strong></div>
        <div className="ai-block"><span className="label">USER</span><h3>{status?.is_auth?status.user:'No authenticated user'}</h3><p className={status?.is_auth?'ok-text':'muted'}>{status?.is_auth?'✓ Authenticated':status?.auth_msg||'Waiting for face'}</p></div>
        <div className="ai-block"><span className="label">PPE</span><div className="detail-check"><span>Mask</span><strong className={status?.mask?'ok-text':'bad-text'}>{camera.check_mask?(status?.mask?'✓ PASS':'— WAITING'):'DISABLED'}</strong></div><div className="detail-check"><span>Hat</span><strong className={status?.hat?'ok-text':'bad-text'}>{camera.check_hat?(status?.hat?'✓ PASS':'— WAITING'):'DISABLED'}</strong></div></div>
        <div className="ai-block"><span className="label">HAND WASHING</span><div className="duration-row"><strong>{fmt(status?.wash_time)}</strong><span>Target {fmt(max)}</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${pct}%`}}/></div><small>Minimum {fmt(min)} · {status?.wash_status||'Standby'}</small></div>
        <div className="ai-block"><span className="label">WHO HAND WASHING</span><div className="who-score"><strong>{status?.master_ready?'6 / 6':'Monitoring'}</strong><span>{status?.master_ready?'Completed':'AI step classification active'}</span></div></div>
        <div className={'final-compliance '+(status?.master_ready?'pass':status?.is_auth?'attention':'idle')}><span>FINAL COMPLIANCE</span><strong>{status?.master_ready?'✓ COMPLIANT':status?.is_auth?'ACTION REQUIRED':'STANDBY'}</strong></div>
      </aside>
    </div>
    <div className="detail-lower-grid">
      <section className="card"><div className="section-heading compact"><div><span className="eyebrow">SESSION INFORMATION</span><h2>Current Session</h2></div></div><div className="info-grid"><div><span>User</span><strong>{status?.is_auth?status.user:'—'}</strong></div><div><span>Role</span><strong>—</strong></div><div><span>Login time</span><strong>{status?.is_auth?'Active now':'—'}</strong></div><div><span>Washing start</span><strong>{status?.wash_time>0?'In progress':'—'}</strong></div><div><span>Current duration</span><strong>{fmt(status?.wash_time)}</strong></div><div><span>Completion</span><strong>{status?.master_ready?'Achieved':'—'}</strong></div></div></section>
      <section className="card"><div className="section-heading compact"><div><span className="eyebrow">AI EVENT TIMELINE</span><h2>Live Decisions</h2></div></div><div className="timeline">{timeline.length?timeline.map((r,i)=><div className="timeline-row" key={i}><span className="timeline-dot"/><time>{r[0]}</time><strong>{r[1]}</strong><small>{r[2]}</small></div>):<div className="muted">Waiting for AI events…</div>}</div></section>
    </div>
    {events.length>0&&<section className="card recent-events"><div className="section-heading compact"><div><span className="eyebrow">RECENT HISTORY</span><h2>Completed Sessions</h2></div></div><table className="data-table"><thead><tr><th>Date</th><th>Time</th><th>User</th><th>Role</th><th>Wash</th><th>WHO</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.time}</td><td>{e.first_name} {e.last_name}</td><td>{e.role}</td><td>{e.wash_duration}s</td><td>{e.all_who_steps}</td></tr>)}</tbody></table></section>}
  </div>
}
