import { useEffect, useState } from 'react'
import { api } from '../api/client'
import { addRoom, getRooms, removeRoom, syncRoomsFromCameras } from '../utils/roomRegistry'

function RoomRegistry({ cameras }){
  const [rooms,setRooms]=useState(()=>getRooms()),[form,setForm]=useState({name:'',department:'',floor:'',area:''}),[error,setError]=useState('')
  const refresh=()=>setRooms(getRooms())
  useEffect(()=>{syncRoomsFromCameras(cameras);refresh()},[cameras.length])
  const add=e=>{e.preventDefault();setError('');try{addRoom(form);setForm({name:'',department:'',floor:'',area:''});refresh()}catch(err){setError(err.message)}}
  const del=r=>{if(cameras.some(c=>c.room===r.name)){alert(`Room "${r.name}" is assigned to one or more cameras. Reassign those cameras before deleting the room.`);return}if(confirm(`Delete room "${r.name}" from the registry?`)){removeRoom(r.id);refresh()}}
  return <div className="room-registry-layout"><form className="card room-form" onSubmit={add}><div className="card-title">Define a room</div><p className="muted setting-help">Create the hospital room first. Cameras can only be assigned to rooms in this registry.</p><div className="form-grid"><label className="field"><span>Room name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="ICU North / CCU / Surgery" required/></label><label className="field"><span>Department</span><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Critical Care / Surgery" required/></label><label className="field"><span>Floor</span><input value={form.floor} onChange={e=>setForm({...form,floor:e.target.value})} placeholder="Level 2"/></label><label className="field"><span>Area / Wing</span><input value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="North Wing"/></label></div>{error&&<p className="error-text">{error}</p>}<button className="btn btn-primary">+ Add Room</button></form>
    <div className="card registry-card"><div className="card-title">Room Registry</div><p className="muted setting-help">{rooms.length} rooms available for camera assignment.</p><div className="registry-list">{rooms.map(r=>{const count=cameras.filter(c=>c.room===r.name).length;return <div className="registry-row" key={r.id}><div className="registry-icon">R</div><div><strong>{r.name}</strong><span>{r.department}{r.floor?` · ${r.floor}`:''}{r.area?` · ${r.area}`:''}</span></div><div className="registry-count"><strong>{count}</strong><span>cameras</span></div><button className="btn btn-sm btn-danger" onClick={()=>del(r)}>Delete</button></div>})}{!rooms.length&&<div className="quiet-row">No rooms defined yet.</div>}</div></div>
  </div>
}

function RegistrationPanel({ cameras }){const [cameraId,setCameraId]=useState(''),[firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[role,setRole]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false);const capture=async e=>{e.preventDefault();setBusy(true);setResult(null);try{const res=await api.registration.capture({camera_id:Number(cameraId),first_name:firstName,last_name:lastName,role});setResult({ok:true,message:`Saved ${res.file_name} for ${res.full_name} (angle #${res.angle_saved})`});setFirstName('');setLastName('');setRole('')}catch(err){setResult({ok:false,message:err.message})}finally{setBusy(false)}};return <div className="card"><div className="card-title">Register staff</div><p className="muted setting-help">Capture the current live frame from a selected camera as a face reference.</p><form onSubmit={capture}><div className="form-grid"><label className="field full"><span>Camera / Room</span><select value={cameraId} onChange={e=>setCameraId(e.target.value)} required><option value="">Select camera…</option>{cameras.map(c=><option key={c.id} value={c.id}>{c.room||'Unassigned'} / {c.name}</option>)}</select></label><label className="field"><span>First name</span><input value={firstName} onChange={e=>setFirstName(e.target.value)} required/></label><label className="field"><span>Last name</span><input value={lastName} onChange={e=>setLastName(e.target.value)} required/></label><label className="field full"><span>Role</span><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Surgeon, Nurse…"/></label></div><button className="btn btn-primary" disabled={busy}>{busy?'Capturing…':'Capture & Save'}</button></form>{result&&<p className={result.ok?'success-text':'error-text'}>{result.message}</p>}<button type="button" className="btn btn-sm" style={{marginTop:10}} onClick={()=>api.registration.resetCache().then(()=>alert('Face cache rebuilt from disk.'))}>Rebuild face recognition cache</button></div>}

export default function Settings(){const [cameras,setCameras]=useState([]),[settings,setSettings]=useState(null),[saving,setSaving]=useState(false);const load=()=>api.cameras.list().then(c=>{setCameras(c);syncRoomsFromCameras(c)});useEffect(()=>{load();api.settings.get().then(setSettings)},[]);const num=v=>v===''?'':Number(v);const save=async e=>{e.preventDefault();setSaving(true);await api.settings.update(settings);setSaving(false)};return <div><div className="page-header"><div><span className="eyebrow">ADMINISTRATION / HOSPITAL CONFIGURATION</span><h1 className="page-title">Settings</h1><div className="page-subtitle">Define rooms first, then configure AI, notifications and staff registration</div></div></div>
  <div className="settings-section-label">ROOM REGISTRY</div><RoomRegistry cameras={cameras}/>
  <div className="section-divider"/>
  {settings&&<form onSubmit={save}><div className="settings-section-label">AI DETECTION</div><div className="settings-grid"><div className="card"><div className="card-title">Detection defaults</div>{[['check_mask_default','Verify medical mask'],['check_hat_default','Verify surgical hat'],['check_wash_default','Verify hand washing']].map(([k,l])=><label className="switch-row setting-switch" key={k}><span>{l}</span><input type="checkbox" checked={!!settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.checked})}/></label>)}</div><div className="card"><div className="card-title">Confidence thresholds</div><div className="form-grid"><label className="field"><span>YOLO confidence</span><input type="number" step="0.05" value={settings.yolo_conf_threshold} onChange={e=>setSettings({...settings,yolo_conf_threshold:num(e.target.value)})}/></label><label className="field"><span>Face confidence</span><input type="number" step="0.05" value={settings.face_detection_confidence} onChange={e=>setSettings({...settings,face_detection_confidence:num(e.target.value)})}/></label><label className="field full"><span>Hand detection confidence</span><input type="number" step="0.05" value={settings.hand_detection_confidence} onChange={e=>setSettings({...settings,hand_detection_confidence:num(e.target.value)})}/></label></div></div></div>
  <div className="settings-section-label">HAND WASHING</div><div className="card settings-three"><label className="field"><span>Minimum wash time (s)</span><input type="number" value={settings.min_wash_time} onChange={e=>setSettings({...settings,min_wash_time:num(e.target.value)})}/></label><label className="field"><span>Maximum wash time (s)</span><input type="number" value={settings.max_wash_time} onChange={e=>setSettings({...settings,max_wash_time:num(e.target.value)})}/></label><label className="field"><span>Presence timeout (s)</span><input type="number" value={settings.presence_timeout} onChange={e=>setSettings({...settings,presence_timeout:num(e.target.value)})}/></label></div>
  <div className="settings-section-label">NOTIFICATIONS</div><div className="card settings-three"><label className="field"><span>Bot API URL</span><input value={settings.bot_api_url||''} onChange={e=>setSettings({...settings,bot_api_url:e.target.value})}/></label><label className="field"><span>Chat ID</span><input value={settings.bot_chat_id||''} onChange={e=>setSettings({...settings,bot_chat_id:e.target.value})}/></label><label className="field"><span>Timeout (s)</span><input type="number" value={settings.bot_timeout} onChange={e=>setSettings({...settings,bot_timeout:num(e.target.value)})}/></label></div><button className="btn btn-primary settings-save" disabled={saving}>{saving?'Saving…':'Save AI & Notification Settings'}</button></form>}
  <div className="section-divider"/><div className="settings-section-label">STAFF REGISTRATION</div><RegistrationPanel cameras={cameras}/></div>}
